from ДомЗаданиеПолиморфизм import Animals,Cat,Dog,People
cat1=Cat("kitty",family="Cats")
cat1.description()
dog1=Dog("Jessy",family="Doggy")
dog1.description()
people1=People("Grisha")
people1.description()
cat2=Animals("Kot9")
cat2.description()
dog2=Animals("Jesika")
dog2.description()
people2=Animals("Stepa")
people2.description()